namespace referendus_netcore
{
	using Microsoft.EntityFrameworkCore;
	using System;
	using System.Collections.Generic;
	using System.Linq;

	public class SqlUserData : IUserData
	{
		PsqlContext _context;

		public SqlUserData(PsqlContext context)
		{
			_context = context;
		}

		public User Add(User user)
		{
			_context.Users.Add(user);
			_context.SaveChanges();
			// Entity Framework will autopopulate Id with what was generated by the SQL server
			return user;
		}

		public User Get(string id)
		{
			return _context.Users.FirstOrDefault(u => u.OAuthId == id);
		}

		public IEnumerable<User> GetAll()
		{
			return _context.Users;
		}

		public User Update(User user)
		{
			_context.Attach(user).State = EntityState.Modified;
			_context.SaveChanges();
			return user;
		}
	}
}
